name: build

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python3 and necessary library

        uses: actions/setup-python@v4

        with:
          python-version: '3.11.2'
          architecture: 'x64'

      - run: pip install -U pip

      - run: pip install Pynacl
    
      - run: pip install yt-dlp

      - run: pip install discord.py[voice]

      - name: Run bot
  env:
      DISCORD_BOT_TOKEN: $ {{ secrets.DISCORD_BOT_TOKEN}}
  run: python main.py